// Mirrors gpui::style — the style system that drives layout and painting.
// In Zed, Style has all fields required, StyleRefinement has all fields Optional.
// The Styled trait provides a Tailwind CSS-inspired builder API.

use crate::color::Hsla;
use crate::geometry::{Corners, Edges, Size};

/// Mirrors gpui::Display — how an element participates in layout
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum Display {
    #[default]
    Flex,
    None,
}

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum Position {
    #[default]
    Relative,
    Absolute,
}

/// Mirrors gpui::FlexDirection — main axis direction
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum FlexDirection {
    #[default]
    Row,
    Column,
}

/// Simplified alignment — Zed has AlignItems with Start/Center/End/Baseline/Stretch
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[allow(dead_code)]
pub enum AlignItems {
    #[default]
    Start,
    Center,
    End,
    Stretch,
}

/// Main axis alignment (justify-content in CSS)
#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[allow(dead_code)]
pub enum JustifyContent {
    #[default]
    Start,
    Center,
    End,
    SpaceBetween,
}

/// Mirrors gpui::style::Style — the full resolved style for an element.
/// Every field has a concrete value (no Option), analogous to CSS computed styles.
#[derive(Clone, Debug)]
pub struct Style {
    pub display: Display,
    pub position: Position,
    pub flex_direction: FlexDirection,
    pub size: Size,
    pub min_size: Size,
    pub max_size: Size,
    pub margin: Edges,
    pub padding: Edges,
    pub border_widths: Edges,
    pub corner_radii: Corners,
    pub inset: Edges,
    pub background: Hsla,
    pub border_color: Hsla,
    pub text_color: Hsla,
    pub font_size: f32,
    pub align_items: AlignItems,
    pub justify_content: JustifyContent,
}

impl Default for Style {
    fn default() -> Self {
        Self {
            display: Display::Flex,
            position: Position::default(),
            flex_direction: FlexDirection::Row,
            size: Size {
                width: f32::MAX,
                height: f32::MAX,
            },
            min_size: Size::ZERO,
            max_size: Size {
                width: f32::MAX,
                height: f32::MAX,
            },
            margin: Edges::default(),
            padding: Edges::default(),
            border_widths: Edges::default(),
            corner_radii: Corners::default(),
            inset: Edges::default(),
            background: Hsla::transparent(),
            border_color: Hsla::transparent(),
            text_color: Hsla {
                h: 0.0,
                s: 0.0,
                l: 0.96,
                a: 1.0,
            },
            font_size: 14.0,
            align_items: AlignItems::default(),
            justify_content: JustifyContent::default(),
        }
    }
}

/// Mirrors gpui::StyleRefinement — optional overrides applied on top of Style defaults.
/// In Zed, this is auto-generated by the Refineable derive macro.
/// The Styled trait's builder methods modify this struct.
#[derive(Clone, Debug, Default)]
pub struct StyleRefinement {
    pub display: Option<Display>,
    pub position: Option<Position>,
    pub flex_direction: Option<FlexDirection>,
    pub size: Option<Size>,
    pub min_size: Option<Size>,
    pub max_size: Option<Size>,
    pub margin: Option<Edges>,
    pub padding: Option<Edges>,
    pub border_widths: Option<Edges>,
    pub corner_radii: Option<Corners>,
    pub inset: Option<Edges>,
    pub background: Option<Hsla>,
    pub border_color: Option<Hsla>,
    pub text_color: Option<Hsla>,
    pub font_size: Option<f32>,
    pub align_items: Option<AlignItems>,
    pub justify_content: Option<JustifyContent>,
}

impl StyleRefinement {
    /// Apply this refinement on top of Style defaults, producing a resolved Style.
    /// Mirrors Zed's cascade: base_style.refine(&refinement).
    pub fn resolve(&self) -> Style {
        let mut style = Style::default();
        if let Some(v) = self.display {
            style.display = v;
        }
        if let Some(v) = self.position {
            style.position = v;
        }
        if let Some(v) = self.flex_direction {
            style.flex_direction = v;
        }
        if let Some(v) = &self.size {
            style.size = *v;
        }
        if let Some(v) = &self.min_size {
            style.min_size = *v;
        }
        if let Some(v) = &self.max_size {
            style.max_size = *v;
        }
        if let Some(v) = self.margin {
            style.margin = v;
        }
        if let Some(v) = self.padding {
            style.padding = v;
        }
        if let Some(v) = self.border_widths {
            style.border_widths = v;
        }
        if let Some(v) = self.corner_radii {
            style.corner_radii = v;
        }
        if let Some(v) = self.inset {
            style.inset = v;
        }
        if let Some(v) = self.background {
            style.background = v;
        }
        if let Some(v) = self.border_color {
            style.border_color = v;
        }
        if let Some(v) = self.text_color {
            style.text_color = v;
        }
        if let Some(v) = self.font_size {
            style.font_size = v;
        }
        if let Some(v) = self.align_items {
            style.align_items = v;
        }
        if let Some(v) = self.justify_content {
            style.justify_content = v;
        }
        style
    }
}

/// Mirrors gpui::Styled — the primary styling API.
/// Provides a builder pattern for setting style properties, returning &mut self for chaining.
#[allow(dead_code)]
pub trait Styled: Sized {
    fn style_refinement(&mut self) -> &mut StyleRefinement;

    // Display
    fn flex(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().display = Some(Display::Flex);
        self
    }

    fn hidden(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().display = Some(Display::None);
        self
    }

    // Position
    fn absolute(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().position = Some(Position::Absolute);
        self
    }

    // Inset (for absolute positioning)
    fn top(mut self, top: f32) -> Self
    where
        Self: Sized,
    {
        let r = self.style_refinement();
        r.inset = Some(r.inset.map_or(
            Edges {
                top,
                ..Edges::default()
            },
            |mut e| {
                e.top = top;
                e
            },
        ));
        self
    }

    fn left(mut self, left: f32) -> Self
    where
        Self: Sized,
    {
        let r = self.style_refinement();
        r.inset = Some(r.inset.map_or(
            Edges {
                left,
                ..Edges::default()
            },
            |mut e| {
                e.left = left;
                e
            },
        ));
        self
    }

    fn inset(mut self, inset: Edges) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().inset = Some(inset);
        self
    }

    // Flex direction
    fn flex_row(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().flex_direction = Some(FlexDirection::Row);
        self
    }

    fn flex_col(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().flex_direction = Some(FlexDirection::Column);
        self
    }

    // Sizing
    fn w(mut self, width: f32) -> Self
    where
        Self: Sized,
    {
        let r = self.style_refinement();
        r.size = Some(Size {
            width,
            height: r.size.map_or(f32::MAX, |s| s.height),
        });
        self
    }

    fn h(mut self, height: f32) -> Self
    where
        Self: Sized,
    {
        let r = self.style_refinement();
        r.size = Some(Size {
            width: r.size.map_or(f32::MAX, |s| s.width),
            height,
        });
        self
    }

    fn size(mut self, width: f32, height: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().size = Some(Size { width, height });
        self
    }

    // Padding (Tailwind-style: p_4 = 16px, px = horizontal, py = vertical)
    fn p(mut self, padding: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().padding = Some(Edges::uniform(padding));
        self
    }

    fn px(mut self, px: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().padding = Some(Edges {
            left: px,
            right: px,
            ..Edges::default()
        });
        self
    }

    fn py(mut self, py: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().padding = Some(Edges {
            top: py,
            bottom: py,
            ..Edges::default()
        });
        self
    }

    // Margin
    fn m(mut self, margin: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().margin = Some(Edges::uniform(margin));
        self
    }

    // Text style
    fn text_color(mut self, color: Hsla) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().text_color = Some(color);
        self
    }

    fn font_size(mut self, font_size: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().font_size = Some(font_size);
        self
    }

    // Background
    fn bg(mut self, color: Hsla) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().background = Some(color);
        self
    }

    // Border
    fn border(mut self, width: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().border_widths = Some(Edges::uniform(width));
        self
    }

    fn border_color(mut self, color: Hsla) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().border_color = Some(color);
        self
    }

    // Corner radii
    fn rounded(mut self, radius: f32) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().corner_radii = Some(Corners::uniform(radius));
        self
    }

    // Alignment
    fn items_center(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().align_items = Some(AlignItems::Center);
        self
    }

    fn items_start(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().align_items = Some(AlignItems::Start);
        self
    }

    fn items_end(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().align_items = Some(AlignItems::End);
        self
    }

    // Justify content (main axis alignment)
    #[allow(dead_code)]
    fn justify_center(mut self) -> Self
    where
        Self: Sized,
    {
        self.style_refinement().justify_content = Some(JustifyContent::Center);
        self
    }
}
